# Generated by Django 4.1.7 on 2024-03-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('jssid', models.CharField(max_length=11, verbose_name='JSSID')),
                ('grade', models.CharField(max_length=3, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('ct', models.BooleanField(verbose_name='Class Teacher')),
                ('teaches', models.CharField(blank=True, max_length=3, null=True, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('students', models.ManyToManyField(related_name='notes_students', to='core.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('grade', models.CharField(max_length=3, verbose_name='Class')),
                ('date', models.DateField(verbose_name='Date')),
                ('present', models.BooleanField(verbose_name='Present')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
        ),
    ]
