# Generated by Django 4.1.7 on 2024-03-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ct',
            field=models.BooleanField(default=0, verbose_name='Class Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teachers'),
        ),
    ]
