# Generated by Django 4.1.7 on 2024-03-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('message', models.CharField(max_length=2048, verbose_name='Message')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen')),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by', to='core.teachers')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to='core.teachers')),
            ],
        ),
    ]
