# Generated by Django 4.1.7 on 2024-03-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recieved_by',
            new_name='received_by',
        ),
    ]
